import pyperclip as pypc
class MyFunction:
    '''
    This function is generated by Chandrashekhar Robbi
    it has functions like
    new(string) -> For creating new comment, markdown
    printArr() -> to print the content of the arr
    removeLastelement() -> remove the last element from the list
    removeByUsingIndex(x) -> remove by using index
    makeNullArr() -> to make empty list
    '''
    def __init__(self):
        self.arr = []
        
    def new(self, s):
        comment = f"7. [{s}](#{s.replace(' ','-')})"
        markdown = f"#### {s}"
        if comment not in self.arr:
            print(s)
            print(comment)
            print(markdown)
            pypc.copy(f"#### {s}")
            self.arr.append(comment)
            print("Successfully added to the comment list")
        else:
            print('It is already in the list')
    def printArr(self):
        for i in self.arr:
            print(i)
            
            
    def removeLastelement(self):
        self.arr.pop()
        
    def removeByUsingIndex(self, x):
        self.arr.pop(x)
    
    def makeNullArr(self):
        self.arr = []
